### ISSUE TITLE
Support for seconds and milliseconds in gantt

### ISSUE THREAD

**Issue by Iorda** [React9k/react-timeline-9000#196]
I'm a collaborator with @cristian-spiescu. The gantt doesn't go beyond minutes and you cannot zoom out after going past this point.
![2020-09-11 14_55_34-React Timeline 9000](https://user-images.githubusercontent.com/11580117/92922661-dbbd7e00-f43e-11ea-81f1-05187d45cc2e.png)

This issue has been fixed in my branch. I also added a new snap variable called "snap"(see problems below)

## Problems
Since the snap was titled "snapMinutes" , I added a new var called "snap". "snapMinutes" still exist to not damage current projects, but the new variable takes seconds. The problem I had is, that I could not get it to below seconds, because of rounded pixel calculations. Meaning, even if i gave it 500 ms to snap, it would go to 0,7s, because it was rounded.

**Comment by kashifshamaz21** [comment]
@lilfolr @marklawlor I would also like to have this feature, as we have events tracked at "seconds" granularity too. Can we look at merging the PR sent by @Iorda for adding support for it? Thanks in advace.

**Comment by lilfolr** [comment]
Added comments to the PR. 
Just need to update the unit tests & some variable names and I think its good to go

**Comment by cristian-spiescu** [comment]
Thanks Leighton for the merge. Can you also close this issue?
