### ISSUE TITLE
[rt10000] Introduce storybook for demo

### ISSUE THREAD

**Issue by cristian-spiescu** [React9k/react-timeline-9000#234]
We will soon create a PR for a feature that we've documented [here](https://github.com/flower-platform/react-timeline-9001/blob/default-item-renderer/docs/default-item-renderer.md). 

We are realizing that maybe a better way to do it is via storybook. I'd like to add [storybook](https://storybook.js.org/) to this project. Does someone see potential issues?

Maybe some build / CI scripts will need to be updated, so that an auto publish of the storybook can take place.

**Comment by cristian-spiescu** [comment]
We completed this operation, and submitted this PR: https://github.com/BHP-DevHub/react-timeline-9000/pull/237

However, I see that there are a lot of checks (related to code formatting) that fail. A few were introduced by our new files. But a lot of them exist in the files that already exist on master. So I'd say that the code from master is not compliant w/ the rules applied by the checks.

What should we do? Should we ignore this? Should someone first fix on master? This someone = you guys @rt9000? Or should we do that? Although most of the fixes seem applicable directly from the GitHub UI.

**Comment by cristian-spiescu** [comment]
However the option to ignore is a no go (I think). Because because of the check failing, the rest of the CI steps were not ran, i.e. running tests, etc.

And one more question: the CI script doesn't perform automatically a deploy somewhere? I think that http://bhp-react-timeline-9k.s3-website-ap-southeast-2.amazonaws.com/ doesn't contain the latest master build. Is it manually deployed here?

I'm standing by for your answers, before submitting 2 more PRs.

**Comment by eliza-marcu** [comment]
Hi!
I'm collaborating with @cristian-spiescu. We have submitted two PRs: [#237](https://github.com/React9k/react-timeline-9000/pull/237) and [#239](https://github.com/React9k/react-timeline-9000/pull/239). Have you had a chance to look at them?

**Comment by lilfolr** [comment]
Hi, Can you rebase them? 
I update the CI/CD jobs but think you need to rebase before they'll run

**Comment by cristian-spiescu** [comment]
Hi!
I have updated the 2 PRs above, i.e. #237 and #239. Could you take a look an integrate in master?

**Comment by leighton-woodside** [comment]
Thanks! Will look at both PRs on the weekend :)

**Comment by cristian-spiescu** [comment]
That's great. A small recap of pending PRs + corresponding issues:

PR #237 - this issue
PR #239 - issue #196
PR #241 - issue #221
PR #245 - issue #190

**Comment by cristian-spiescu** [comment]
Hi there! Do you think you'll have a bit of time to take a look at the PRs above?

**Comment by lilfolr** [comment]
Hey, 
The first 2 have been merged, and the second 2 have conflicts. If you rebase them I'll review & merge :)

**Comment by eliza-marcu** [comment]
Hello,
We have resolved the conflicts, you can go ahead with the review.
