### ISSUE TITLE
[rt10000] Update to babel v7

### ISSUE THREAD

**Issue by cristian-spiescu** [React9k/react-timeline-9000#271]
Hi there,

Do you see any issue in upgrading from babel 6 to babel 7? The storybook already works w/ babel 7 and I didn't notice any issues. 

The motivation is [this issue](https://github.com/storybookjs/storybook/issues/16348). Having 2 '.babelrc' files makes cumbersome the work w/ storybook.

**Comment by eliza-marcu** [comment]
We have added PR https://github.com/React9k/react-timeline-9000/pull/272 for this issue.

**Comment by cristian-spiescu** [comment]
Thanks for merging. Closing the issue.
